apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260505-145121-4mw60i84wpll-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260505-145121-4mw60i84wpll.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260505-145121-4mw60i84wpll-service
            port:
              number: 80
